export const API_DATE = "20170825";
export const API_ROOT = "https://api.foursquare.com/v2/venues/explore";
export const CLIENT_ID = "NTYNR3W1X3ENQNXY1OMOCGAZIRCUKRRUPCSBLAYGLDXDSCQ2";
export const CLIENT_SECRET = "CAA4E5WUPADA4X0TYWBM0PG2H44R5ICBRJYNMCKQFCZCFIAN";