export const SET_ORDER = 'SET_ORDER';
export const SET_FILTER_PRICE = 'SET_FILTER_PRICE';

export const DATA_RECEIVED = 'DATA_RECEIVED';
export const DATA_FETCH_FAIL = 'DATA_FETCH_FAIL';
export const DATA_FETCH_STARTED = 'DATA_FETCH_STARTED';

export const LOCATION_RECEIVED = 'LOCATION_RECEIVED';
export const SET_MANUAL_LOCATION = 'SET_MANUAL_LOCATION';

export const START_WITHOUT_LOCATION = 'START_WITHOUT_LOCATION';